{"timestamp":"2025-07-21T04:34:49.499716","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-21T04:34:49.499968","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/covid_data_pipeline.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-21T04:34:49.864650Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.864820Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.865010Z","level":"info","event":"Current task name:create_employees_table","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.865136Z","level":"info","event":"Dag name:process_employees","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.864940","level":"info","event":"Executing: \n            CREATE TABLE IF NOT EXISTS employees (\n                \"Serial Number\" NUMERIC PRIMARY KEY,\n                \"Company Name\" TEXT,\n                \"Employee Markme\" TEXT,\n                \"Description\" TEXT,\n                \"Leave\" INTEGER\n            );","logger":"airflow.task.operators.airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator"}
{"timestamp":"2025-07-21T04:34:49.870901","level":"info","event":"Connection Retrieved '1'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-21T04:34:49.873622","level":"info","event":"Connection Retrieved '1'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-21T04:34:49.874236","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"localhost\" (::1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py","lineno":317,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":767,"name":"run"},{"filename":"/usr/local/lib/python3.12/contextlib.py","lineno":137,"name":"__enter__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":874,"name":"_create_autocommit_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":177,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-21T04:34:49.874805Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.874953Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.875049Z","level":"info","event":"Task:<Task(SQLExecuteQueryOperator): create_employees_table>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.875154Z","level":"info","event":"Failure caused by connection to server at \"localhost\" (::1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.875253Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.875464Z","level":"info","event":"connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.875568Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-21T04:34:49.875616Z","level":"info","event":"","chan":"stdout","logger":"task"}
