{"timestamp":"2025-07-17T04:26:52.848051","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-17T04:26:52.848979","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/covid_data_pipeline.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-17T04:26:53.240600Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.240759Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.240910Z","level":"info","event":"Current task name:create_employees_temp_table","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.241039Z","level":"info","event":"Dag name:process_employees","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.240844","level":"info","event":"Executing: \n            DROP TABLE IF EXISTS employees_temp;\n            CREATE TABLE employees_temp (\n                \"Serial Number\" NUMERIC PRIMARY KEY,\n                \"Company Name\" TEXT,\n                \"Employee Markme\" TEXT,\n                \"Description\" TEXT,\n                \"Leave\" INTEGER\n            );","logger":"airflow.task.operators.airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator"}
{"timestamp":"2025-07-17T04:26:53.247083","level":"info","event":"Connection Retrieved '1'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-17T04:26:53.250079","level":"info","event":"Connection Retrieved '1'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-17T04:26:53.250466","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"localhost\" (::1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py","lineno":317,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":767,"name":"run"},{"filename":"/usr/local/lib/python3.12/contextlib.py","lineno":137,"name":"__enter__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":874,"name":"_create_autocommit_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":177,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-17T04:26:53.250977Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.251128Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.251224Z","level":"info","event":"Task:<Task(SQLExecuteQueryOperator): create_employees_temp_table>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.251330Z","level":"info","event":"Failure caused by connection to server at \"localhost\" (::1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.251430Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.251673Z","level":"info","event":"connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.251727Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T04:26:53.251833Z","level":"info","event":"","chan":"stdout","logger":"task"}
